description = "Just One Guy's Musings..."
favicon = "images/favicon.png"
images = ["images/share.png"]
title = "msnws"
colorScheme = "noir"
enableSearch = "true"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur
  
  [footer]
 	 showMenu = true
 	 showCopyright = true
 	 showThemeAttribution = false
 	 showAppearanceSwitcher = true
 	 showScrollToTop = true

[homepage]
	layout = "profile"
	showRecent = true
	showRecentItems = 12
	showMoreLink = true
	showMoreLinkDest = "/blog"
	cardView = false
	cardViewScreenWidth = true

[article]
	showDate = true
	showViews = false
	showLikes = false
	showDateUpdated = false
	showAuthor = false
	showHero = true
	heroStyle = "basic"
	showBreadcrumbs = true
	showDraftLabel = true
	showEdit = false
	seriesOpened = false
	showHeadingAnchors = true
	showPagination = true
	invertPagination = false
	showReadingTime = true
	showTableOfContents = true
	showRelatedContent = true
	relatedContentLimit = 3
	showTaxonomies = false
	showWordCount = false
	#sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
	
[list]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false
  
  [taxonomy]
 	 showTermCount = true
 	 showHero = true
	  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
 	 showBreadcrumbs = false
 	 showViews = true
 	 showLikes = true
 	 showTableOfContents = true
 	 cardView = false
	
